import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import SiteHeader from "../components/header"
import { ClerkProvider } from "@clerk/nextjs";
import Page from "components/chatbot";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Artify - AI & Blockchain Based Art Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SiteHeader />
            {children}
            <Page />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
